apiVersion: v2
name: exporter-trigger
description: A Helm chart for exporter-trigger service
type: application
version: 3.2.0
appVersion: 3.2.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
